APP_MODULES                    := ssl crypto openssl ssltest
APP_PLATFORM 	               := android-9
APP_OPTIM 		               := debug
APP_STL                        := gnustl_shared
APP_GNUSTL_CPP_FEATURES        := exceptions rtti 
APP_ABI                        := armeabi
APP_CPPFLAGS                   += -fexceptions
APP_CPPFLAGS                   += -frtti
APP_CFLAGS					   := -g -Wall -lc